## first stage
FROM node:16-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
COPY package-lock*.json ./

RUN npm install --force

COPY . .

ARG BASE_URL
ENV KERBB_MAIN_BASE_URL=${BASE_URL}

RUN npm run build

VOLUME [ "/app/kerbb-react-admin/build" ]
